config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true, length: {maximum: 20}
    validates :start_date, presence: true
    validates :end_date, presence: true
    validate :start_end_check
    validates :memo, length: {maximum: 500}

    def start_end_check
        if self.start_date.present? && self.end_date.present?
            errors.add(:end_date, "は開始日よりも前の日付は登録できません") unless
            self.end_date >= self.start_date
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params.require(:task).permit(:title, :start_date, :end_date, :is_all_day, :memo))
      if @task.save
        flash[:notice] = "予定を作成しました"
        redirect_to :tasks
      else
        flash.now[:alert] = "予定の作成に失敗しました"
        render "new"
      end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:title, :start_date, :end_date, :is_all_day, :memo))
      flash[:notice] = "予定(#{@task.id})の情報を更新しました"
      redirect_to :tasks
    else
      flash.now[:alert] = "予定の編集に失敗しました"
      render "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "予定を削除しました"
    redirect_to :tasks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    
    <title>Myapp</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <header>
      <%= render partial: 'shared/partial' %>
    </header>

    <%= yield %>

    <footer>
      <div class= "footer-content">
        <p>予定合計: <%= Task.count %></p>
        /
        <p>本日の日付: <%= Date.today.strftime("%Y/%m/%d") %></p>
      </div>
      
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js"></script>

    <script>
      document.addEventListener('DOMContentLoaded', function () {
        $('#start-date-time').bootstrapMaterialDatePicker({
          weekStart: 0,
          lang: 'ja',
          time: false,
          format: 'YYYY-MM-DD'
        }).on('change', function(e, date) {
          $('#start-date-time').val(date.format('YYYY-MM-DD'));
        });

        $('#end-date-time').bootstrapMaterialDatePicker({
          weekStart: 0,
          lang: 'ja',
          time: false,
          format: 'YYYY-MM-DD'
        }).on('change', function(e, date) {
          $('#end-date-time').val(date.format('YYYY-MM-DD'));
        });
      });
    </script>

  </body>
</html>

app/views/shared/_error.html.erb
<!--
    <% if obj.errors.any? %>
        <% obj.errors.full_messages.each do |message|%>
            <ul>
                <li><%= message %></li>
            </ul>
        <% end%>
    <% end%>
-->

app/views/shared/_partial.html.erb
<div class="partial">
    <h4>スケジュール管理アプリ</h4>
</div>

app/views/tasks/edit.html.erb
<h3>予定編集</h3>

<% flash.each do |message_type, message| %>
  <div class="flash-message-edit" <%= message_type %>"><%= message %></div>
<% end %>

<%= form_with model: @task do |f| %>
  <table>
    <tr>
      <th><%= f.label :title ,"タイトル" %></th>
      <td>
        <%= f.text_field :title %>
        <%if @task.errors.include?(:title)%>
          <div class="error"><%= @task.errors.full_messages_for(:title).first%></div>
        <%end%>
      </td>
    </tr>

    <tr>
      <th><%= f.label :start_date ,"開始日" %></th>
      <td>
        <div class="form-group">
          <%= f.text_field :start_date, class: 'form-control result', value: @task.start_date.strftime('%Y-%m-%d'), id: 'start-date-time' %>
          <%if @task.errors.include?(:start_date)%>
            <div class="error"><%= @task.errors.full_messages_for(:start_date).first%></div>
          <%end%>
        </div>
      </td>
    </tr>

    <tr>
      <th><%= f.label :end_date,"終了日" %></th>
      <td>
        <div class="form-group">
          <%= f.text_field :end_date, class: 'form-control result', value: @task.end_date.strftime('%Y-%m-%d'), id: 'end-date-time' %>
          <%if @task.errors.include?(:end_date)%>
              <div class="error"><%= @task.errors.full_messages_for(:end_date).first%></div>
          <%end%>
        </div>
      </td>
    </tr>

    <tr>
      <th><%= f.label :is_all_day ,"終日" %></th>
      <td><%= f.check_box :is_all_day%></td>
    </tr>

    <tr>
      <th><%= f.label :memo? ,"スケジュールメモ" %></th>
      <td>
        <%= f.text_area :memo %>
        <%if @task.errors.include?(:memo)%>
          <div class="error"><%= @task.errors.full_messages_for(:memo).first%></div>
        <%end%>
      </td>
    </tr>

  </table>

  <div class="edit-bottom">
    <ul>
      <li><%= f.submit "編集を完了する" %></li>
      <li><%= link_to "予定一覧に戻る", tasks_path%></li>
    </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class ="index">

    <h3>予定一覧</h3>

    <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    
    <p><%= button_to "予定の新規追加", :new_task, method: "get" %></p>

    <table>
        <thead>
            <tr>
            <th>id</th>
            <th>タイトル</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>終日</th>
            <th>更新日時</th>
            <th></th>
            <th></th>
            <th></th>
            </tr>
        </thead>

        <tbody>
            <% @tasks.each do |task| %>
                <tr>
                    <td><%= task.id %></td>
                    <td><%= task.title %></td>
                    <td><%= task.start_date.strftime("%Y/%m/%d") %></td>
                    <td><%= task.end_date.strftime("%Y/%m/%d") %></td>
                    <td><%= task.is_all_day ? '◯' : '' %></td>
                    <td><%= task.updated_at.strftime("%Y/%m/%d %H:%M")%></td>
                    <td>
                        <%= link_to "詳細", task%>
                    </td>
                    <td>
                        <%= link_to "編集", [:edit, task] %>
                    </td>
                    
                    <td>
                        <a href="#" data-toggle="modal" data-target="#exampleModal<%= task.id %>">削除</a>
                        <div class="modal fade" id="exampleModal<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">予定を削除しますか？</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">本当に削除しますか？この操作は取り消せません。</div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">やめる</button>
                                <%= link_to "削除", task, method: :delete, class: "btn btn-danger" %>
                            </div>
                            </div>
                        </div>
                        </div>
                    </td>

                </tr>
 
            <% end %>
           
        </tbody>
    </table>

</div>

app/views/tasks/new.html.erb
<h3 class="new-top">予定の新規追加</h3>

<% flash.each do |message_type, message| %>
    <div class="flash-message" <%= message_type %>"><%= message %></div>
<% end %>

<%= form_with model: @task do |f|%>
    <table>
    
        <tr>
            <th><%= f.label :title ,"タイトル" %></th>
            <td>
                <%= f.text_field :title %>
                <%if @task.errors.include?(:title)%>
                    <div class="error"><%= @task.errors.full_messages_for(:title).first%></div>
                <%end%>
            </td>
        </tr>

        <tr>
            <th><%= f.label :start_date ,"開始日" %></th>
            <td>
                <div class="form-group">
                    <%= f.text_field :start_date, class: 'form-control result', placeholder: 'YYYY/MM/DD', id: 'start-date-time' %>
                    <%if @task.errors.include?(:start_date)%>
                        <div class="error"><%= @task.errors.full_messages_for(:start_date).first%></div>
                    <%end%>
                </div>
            </td>
        </tr>

        <tr>
            <th><%= f.label :end_date ,"終了日" %></th>
            <td>
                <div class="form-group">
                    <%= f.text_field :end_date, class: 'form-control result', placeholder: 'YYYY/MM/DD', id: 'end-date-time' %>
                    <%if @task.errors.include?(:end_date)%>
                        <div class="error"><%= @task.errors.full_messages_for(:end_date).first%></div>
                    <%end%>
                </div>
            </td>
        </tr>

        <tr>
            <th><%= f.label :is_all_day ,"終日の場合はチェックを入れます" %></th>
            <td><%= f.check_box :is_all_day %></td>
        </tr>

        <tr>
            <th><%=f.label :memo ,"スケジュールメモ" %></th>
            <td>
                <%= f.text_area :memo %>
                <%if @task.errors.include?(:memo)%>
                    <div class="error"><%= @task.errors.full_messages_for(:memo).first%></div>
                <%end%>
            </td>
        </tr>
       
    </table>

    <div class="botton-container">
        <ul>
            <li><%= f.submit "保存"%></li>
            /
            <li><%= link_to "キャンセル", "/tasks" %></li>
        </ul>
    </div>
<% end%> 

app/views/tasks/show.html.erb
<h3 class="show-top">予定詳細</h3>

<div class="t-container">
 <table>
    <tr>
        <th>タイトル</th>
        <td><%= @task.title %></td>
        </tr>
        <tr>
        <th>開始日</th>
        <td><%= @task.start_date.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
        <th>終了日</th>
        <td><%= @task.end_date.strftime("%Y/%m/%d") %></td>
        </tr>
        <tr>
        <th>終日</th>
        <td><%= @task.is_all_day ? '◯' : '' %></td>
        </tr>
        <tr>
        <th>スケジュールメモ</th>
        <td><%= @task.memo %></td>
    </tr>
 </table>

    <div class="show-bottom">
        <ul>
            <li><%= link_to "予定一覧に戻る", :tasks %></li>
        </ul>
    </div>
</div>